# processors on 1 node
#PBS -l nodes=1:ppn=6

#Request walltime/fastq file ~30 min/sample
#PBS -l walltime=240:00:00

#Request 1 gigabyte of memory per process
#PBS -l mem=16gb

#Request that regular output and terminal output go to the same file
#PBS -j oe
#PBS -M Emily.Laplante@bcm.edu
#PBS -m abe

mkdir /scratch/$PBS_JOBID
find /mnt/brlstor/Vol6_SP/exrna/readCoverage/EmilyTest/biosample_RBP_out_unzipped -name '*_${type}_${status}.tar.gz' -exec cp -at /scratch/$PBS_JOBID {} +

cd /scratch/$PBS_JOBID

cat *.tar.gz | tar -xzvf - -i
rm *tar.gz
files=$(ls *.txt | head -1)

for studyfile in *.txt
do
 test=$(basename $studyfile)
 echo ${test}
 if [ $test == $files ]; then
  #echo "equal"
  cp $studyfile ${type}_${status}.txt
 else
  #echo "Not"
  awk -v OFS="\t" '{ for(i=4; i<=NF; i++) printf "%s",$i (i==NF?ORS:OFS) }' $studyfile > temp_study.txt
  paste ${type}_${status}.txt temp_study.txt > studyfile_temp.txt
  mv studyfile_temp.txt ${type}_${status}.txt
  rm temp_study.txt
 fi
 rm $studyfile
done

#filter
awk 'NR==1 {print } NR>1 { s=0 ; for(i=4;i<=NF;i++) s+=$i ; if (s) print ;}' ${type}_${status}.txt > ${type}_${status}_filtered.txt

echo "Total lines"
wc -l ${type}_${status}.txt
echo "Filtered lines"
wc -l ${type}_${status}_filtered.txt

tar -czvf ${type}_${status}.tar.gz ${type}_${status}.txt
tar -czvf ${type}_${status}_filtered.tar.gz ${type}_${status}_filtered.txt

mv *.tar.gz /mnt/brlstor/Vol6_SP/exrna/readCoverage/EmilyTest/biosample_RBP_out_unzipped

