
##For PHT
totalN=c("EXR-AKRIC157ITEl-AN", "EXR-ANACC1S6lJ1C-AN", "EXR-AWEAV1lyeWbT-AN", "EXR-DERLE1Dj6liR-AN", "EXR-DERLE1PHASE1OPEN-AN", "EXR-DERLE1PHASE1PROT-AN", "EXR-DGALA16xrQga-AN", "EXR-DGALA17UKOTF-AN", "EXR-DGALA1aAMvwl-AN", "EXR-DGALA1adMfMp-AN", "EXR-DGALA1ADV4Eu-AN", "EXR-DGALA1AwypQM-AN", "EXR-DGALA1B2gzMc-AN", "EXR-DGALA1Cs7zRr-AN", "EXR-DGALA1ECRXVs-AN", "EXR-DGALA1EE8DTR-AN", "EXR-DGALA1EwBtDI-AN", "EXR-DGALA1hDe89A-AN", "EXR-DGALA1ljaXqg-AN", "EXR-DGALA1mUDpAe-AN", "EXR-DGALA1QDi9GG-AN", "EXR-DGALA1QPJsAJ-AN", "EXR-DGALA1tFbYSj-AN", "EXR-DGALA1tHZJ9D-AN", "EXR-DGALA1V5h5va-AN", "EXR-DGALA1zS6cGa-AN", "EXR-DWONG1qf3tcS-AN", "EXR-IGHIR1D3SVzD-AN", "EXR-IGHIR1GUqJ5l-AN", "EXR-IGHIR1HnDH6K-AN", "EXR-IGHIR1P6qCmn-AN", "EXR-IGHIR1tbB6UC-AN", "EXR-IGHIR1V7Sc5u-AN", "EXR-IGHIR1zpYRsa-AN", "EXR-JFRAN16VDql8-AN", "EXR-JFRAN1cDpMBU-AN", "EXR-JFREE1dXQ2sI-AN", "EXR-JFREE1eZDUKB-AN", "EXR-JJONE1AcUuui-AN", "EXR-JJONE1HC7DHb-AN", "EXR-JJONE1tHRzcU-AN", "EXR-JJONE1wAX8tF-AN", "EXR-KJENS10lPClY-AN", "EXR-KJENS12WGutU-AN", "EXR-KJENS17CZMbP-AN", "EXR-KJENS1RID1-AN", "EXR-KJENS1sPlvS2-AN", "EXR-KJENS1WBaSro-AN", "EXR-KJENS1yrpQwk-AN", "EXR-KVICK1oIp40e-AN", "EXR-KWANG15hiHRW-AN", "EXR-KWANG1jo8Fqz-AN", "EXR-KWANG1Nb3oPN-AN", "EXR-LLAUR18RWng7-AN", "EXR-LLAUR1s0A1mX-AN", "EXR-LLAUR1SFszrF-AN", "EXR-MBITZ12SHVIr-AN", "EXR-MBITZ1KPWIgP-AN", "EXR-MBITZ1WCKgCw-AN", "EXR-MTEWA1cHYLo6-AN", "EXR-MTEWA1vczugX-AN", "EXR-MTEWA1ZR3Xg6-AN", "EXR-SADAS17lDVDx-AN", "EXR-SADAS1EXER1-AN", "EXR-SADAS1UJ0CzW-AN", "EXR-TPATE1NUsA7E-AN", "EXR-TPATE1OqELFf-AN", "EXR-TTUSC1gCrGDH-AN")

for (n in totalN) {
  str = sprintf("qsub -N %s -v study=%s all_exRNA_coverage.pbs", paste(n,"coverage",sep="_"), n )
  #print(str)
  system(str, wait=FALSE)
  system("sleep 0.2")
}

