args = commandArgs(trailingOnly=TRUE)
sample = args[2]
# getwd()

#totalN = c("EXR-DERLE1Dj6liR-AN","EXR-DGALA1QDi9GG-AN")
#totalN = "EXR-KJENS17CZMbP-AN"
#Already ran "EXR-DERLE1Dj6liR-AN" and "EXR-KJENS10lPClY-AN" durign tes
#totalN = c("EXR-DGALA1V5h5va-AN", "EXR-KVICK1oIp40e-AN", "EXR-JJONE1wAX8tF-AN", "EXR-SADAS1EXER1-AN",
#           "EXR-MTEWA1ZR3Xg6-AN", "EXR-MTEWA1cHYLo6-AN", "EXR-MTEWA1vczugX-AN", "EXR-KJENS1RID1-AN")
# totalN = c("EXR-DGALA1V5h5va-AN", "EXR-KVICK1oIp40e-AN", "EXR-JJONE1wAX8tF-AN", "EXR-SADAS1EXER1-AN",
#            "EXR-MTEWA1ZR3Xg6-AN", "EXR-MTEWA1cHYLo6-AN", "EXR-MTEWA1vczugX-AN", "EXR-KJENS1RID1-AN",
#            "EXR-DERLE1Dj6liR-AN", "EXR-KJENS10lPClY-AN","EXR-KJENS17CZMbP-AN")

###For the cell line studies
#totalN = c("EXR-JFRAN1cDpMBU-AN","EXR-AWEAV1lyeWbT-AN","EXR-AKRIC157ITEl-AN","EXR-JFRAN16VDql8-AN")

##REDO
#totalN = c('EXR-KJENS1RID1-AN','EXR-MTEWA1ZR3Xg6-AN','EXR-MTEWA1cHYLo6-AN')

###For the saliva
#totalN = c('EXR-DERLE1PHASE1PROT-AN','EXR-DWONG1qf3tcS-AN')

###For CSF
#totalN = c('EXR-DGALA17UKOTF-AN','EXR-DGALA1adMfMp-AN','EXR-DGALA1B2gzMc-AN','EXR-DGALA1ECRXVs-AN','EXR-DGALA1mUDpAe-AN','EXR-DGALA1QDi9GG-AN','EXR-KJENS1sPlvS2-AN')

###For urine
#totalN = c('EXR-ANACC1S6lJ1C-AN','EXR-JJONE1HC7DHb-AN','EXR-JJONE1tHRzcU-AN')

###For serum
#totalN = c('EXR-IGHIR1HnDH6K-AN','EXR-JJONE1AcUuui-AN','EXR-LLAUR1s0A1mX-AN')
#Plus EXR-LLAUR1SFszrF-AN which will have to be processed separately

#Studies
#totalN=c("EXR-DERLE1Dj6liR-AN", "EXR-DERLE1PHASE1PROT-AN", "EXR-DGALA17UKOTF-AN", "EXR-DGALA1adMfMp-AN", "EXR-DGALA1B2gzMc-AN", "EXR-DGALA1ECRXVs-AN", "EXR-DGALA1mUDpAe-AN", "EXR-DGALA1QDi9GG-AN", "EXR-DGALA1V5h5va-AN", "EXR-IGHIR1HnDH6K-AN", "EXR-JJONE1AcUuui-AN", "EXR-JJONE1HC7DHb-AN", "EXR-JJONE1tHRzcU-AN", "EXR-JJONE1wAX8tF-AN", "EXR-KJENS12WGutU-AN", "EXR-KJENS17CZMbP-AN", "EXR-KVICK1oIp40e-AN", "EXR-LLAUR1s0A1mX-AN", "EXR-MBITZ12SHVIr-AN", "EXR-MTEWA1ZR3Xg6-AN", "EXR-SADAS1EXER1-AN", "EXR-SADAS1UJ0CzW-AN", "EXR-MTEWA1vczugX-AN")
#totalN=c("EXR-DERLE1PHASE1PROT-AN", "EXR-MTEWA1vczugX-AN", "EXR-TPATE1OqELFf-AN", "EXR-KJENS10lPClY-AN", "EXR-MTEWA1cHYLo6-AN", "EXR-ANACC1S6lJ1C-AN", "EXR-DWONG1qf3tcS-AN")
totalN=c("EXR-DWONG1qf3tcS-AN","EXR-TTUSC1gCrGDH-AN","EXR-KJENS1sPlvS2-AN","EXR-ANACC1S6lJ1C-AN")
#totalN=c("EXR-KJENS10lPClY-AN","EXR-MTEWA1cHYLo6-AN","EXR-KJENS1RID1-AN")
#totalN=c("EXR-MTEWA1ZR3Xg6-AN","EXR-MTEWA1vczugX-AN")
for (n in totalN) {
  str = sprintf("qsub -N %s -v study=%s create_loci_by_study_matrixes_loop.pbs", n, n )
  system(str, wait=FALSE)
  system("sleep 0.2")
}

