# processors on 1 node
#PBS -l nodes=1:ppn=3

#Request walltime/fastq file ~30 min/sample
#PBS -l walltime=1:00:00

#Request 1 gigabyte of memory per process
#PBS -l mem=8gb

#Request that regular output and terminal output go to the same file
#PBS -j oe
#PBS -N relace_loci
#PBS -M Emily.Laplante@bcm.edu
#PBS -m abe

module load R/3.5

cd /scratch/$PBS_JOBID

#Rscript /mnt/brlstor/Vol6_SP/exrna/readCoverage/EmilyTest/RBP_correlations/test_new_randomCor.R
Rscript /mnt/brlstor/Vol6_SP/exrna/readCoverage/EmilyTest/RBP_correlations/test_Create_withinRBP_correlatedPairs.R
